workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
      java: 17
      android_signing:
        - keystore: my-key-alias  # Keystore alias name from your keystore details
          # Optional, if you are using an environment variable for password
          # Keystore alias name
          # Optional, if you are using an environment variable for password
    scripts:
      - name: Clear Flutter and Gradle Cache
        script: |
          flutter clean
          flutter pub get
      - name: Build Release APK
        script: flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
