#file: noinspection YAMLSchemaValidation
workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
      java: 17
      android_signing:
        keystore:
          type: file
          filePath: /tmp/keystore.jks  # Codemagic will set this automatically
          keystore_password: $CM_KEYSTORE_PASSWORD
          key_alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD
    scripts:
      - name: Clear Flutter and Gradle Cache
        script: |
          flutter clean
          flutter pub get
      - name: Build Release APK
        script: flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
