workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
      java: 17
      android_signing:
        - keystore: my_keystore_reference  # Replace with your actual keystore reference
    scripts:
      - name: Clean Flutter and Gradle Cache
        script: |
          flutter clean
          flutter pub get
          rm -rf android/.gradle
          rm -rf android/build
          rm -rf build
      - name: Build Release APK
        script: flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
