workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
      java: 17
      vars:
        # Define environment variables here
        KEYSTORE_PATH: "C:/Users/Gaming/Desktop/project/my_app"  # Full path to your keystore file
        KEYSTORE_PASSWORD: "123456"  # Keystore password
        KEY_ALIAS: "my-key-alias"  # Your key alias
        KEY_PASSWORD: "123456"  # Key password
    scripts:
      - name: Clear Flutter and Gradle Cache
        script: |
          flutter clean
          flutter pub get
      - name: Build Release APK
        script: |
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
